# Generated by Django 4.2.28 on 2026-02-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the project', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional project description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the project was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the project was last updated')),
                ('owner', models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When preference was last updated')),
                ('active_project', models.ForeignKey(blank=True, help_text='Currently selected/active project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='projects.project')),
                ('user', models.OneToOneField(help_text='User whose preference this is', on_delete=django.db.models.deletion.CASCADE, related_name='project_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Project Preference',
                'verbose_name_plural': 'User Project Preferences',
                'db_table': 'user_project_preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project_name_per_user'),
        ),
    ]
