# Generated by Django 4.2.28 on 2026-02-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_databaseconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPIIField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='Name of the table containing the PII field', max_length=255)),
                ('field_name', models.CharField(help_text='Name of the field/column containing PII', max_length=255)),
                ('pii_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('card', 'Credit Card'), ('ssn', 'Social Security Number'), ('name', 'Personal Name'), ('address', 'Physical Address'), ('other', 'Other PII')], help_text='Type of PII detected (email, phone, card, ssn, etc.)', max_length=50)),
                ('confidence', models.FloatField(help_text='Confidence score of the detection (0.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the detection was recorded')),
                ('project', models.ForeignKey(help_text='Project this detected PII field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='detected_pii_fields', to='projects.project')),
            ],
            options={
                'verbose_name': 'Detected PII Field',
                'verbose_name_plural': 'Detected PII Fields',
                'db_table': 'detected_pii_fields',
                'ordering': ['-created_at'],
            },
        ),
    ]
