# Generated by Django 4.2.28 on 2026-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_detectedpiifield'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='database_name',
            field=models.CharField(default='', help_text='Name of the database to connect to', max_length=255),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Database password (stored as plain text for academic purposes)', max_length=255),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='port',
            field=models.IntegerField(blank=True, help_text='Database port (optional, uses default if not specified)', null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Database username', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Connection status', max_length=20),
        ),
    ]
