# Generated by Django 4.2.28 on 2026-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_masking_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskinglog',
            name='action',
            field=models.CharField(choices=[('job_started', 'Job Started'), ('analysis_started', 'Analysis Started'), ('analysis_completed', 'Analysis Completed'), ('strategy_selected', 'Strategy Selected'), ('masking_started', 'Masking Started'), ('masking_completed', 'Masking Completed'), ('validation_started', 'Validation Started'), ('validation_completed', 'Validation Completed'), ('job_completed', 'Job Completed'), ('job_failed', 'Job Failed')], default='job_started', help_text='Specific action being performed', max_length=50),
        ),
        migrations.AddField(
            model_name='maskinglog',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', help_text='Action status', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectedpiifield',
            name='pii_type',
            field=models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('card', 'Credit Card'), ('ssn', 'Social Security Number'), ('name', 'Personal Name'), ('address', 'Physical Address'), ('aadhaar', 'Aadhaar Number'), ('pan', 'PAN Card'), ('other', 'Other PII')], help_text='Type of PII detected (email, phone, card, ssn, etc.)', max_length=50),
        ),
    ]
