# Generated by Django 4.2.28 on 2026-02-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('sqlite', 'SQLite')], help_text='Type of database', max_length=20)),
                ('host', models.CharField(help_text='Database host address', max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed')], default='failed', help_text='Connection status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the connection was created')),
                ('project', models.ForeignKey(help_text='Project this database connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='db_connections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
                'db_table': 'database_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
